name: PythonCICD

on: 
    push: 
    workflow_dispatch:
        inputs:
          score:
            description: 'Pylint Score'     
            required: true
            default: '10'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Execute Test Cases
      run: |
        pytest -v --junit-xml=tests.xml --cov-report=xml --cov=app/core
    - name: Execute Lint
      run: |
        pylint app/core/*.py --fail-under=${{ github.event.inputs.score }}
        sed -i -e 's|<source>.*<\/source>|<source>app/core<\/source>|g' coverage.xml 
  
