name: PythonCICD

on: 
    push: 
    workflow_dispatch:
        inputs:
          score:
            description: 'Pylint Score'     
            required: true
            default: '10'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Execute Test Cases
      run: |
        pytest -v --junit-xml=tests.xml --cov-report=xml --cov=app/core
    - uses: shallwefootball/s3-upload-action@master
      with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: "artifactsmaven"
          source_dir: 'app'
    - name: Execute Lint
      run: |
        score=10
        if [ -z ${{ github.event.inputs.score }} ];
            echo "Value Empty"
        else
            score=${{ github.event.inputs.score }}
        fi
        pylint app/core/*.py --fail-under=${score}
        sed -i -e 's|<source>.*<\/source>|<source>app/core<\/source>|g' coverage.xml 
  
