name: PythonCICD

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Execute Test Cases
      run: |
        pytest -v --junit-xml=tests.xml --cov-report=xml --cov=app/core
    - name: Execute Lint
      run: |
        pylint app/core/*.py --fail-under=3
    - name: SonarQube Scanner
      uses: sonarsource/sonarqube-scan-action@master
      env:
        # SonarQube server URL
        SONAR_HOST_URL: http://54.146.193.237:9000
        # Login or authentication token of a SonarQube user
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
