name: pytesting

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Python Lint
      run: |
        pip install pylint
        pylint app/core/*.py --fail-under=3
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v --cov-report=xml --junitxml=tests.xml --cov=app/core
        sed -i -e 's|<source>.*<\/source>|<source>app/core<\/source>|g' coverage.xml
    - name: SonarQube Scanner
      uses: sonarsource/sonarqube-scan-action@master
      env:
        # SonarQube server URL
        SONAR_HOST_URL: http://35.172.192.145:9000
        # Login or authentication token of a SonarQube user
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
